### ISSUE TITLE
[BUG][1] java.lang.IllegalStateException: REST Docs configuration not found. Did you forget to add a RestAssuredRestDocumentationConfigurer as a filter when building the RequestSpecification?   [2] org.opentest4j.AssertionFailedError: expected:<[-119, 80, 78,  ...] and 460974 more> but was:<[]> ,org.koin.core.error.NoBeanDefFoundException  [3] NotRegisteredException

### ISSUE THREAD

**Issue by mjkim103301** [mjkim103301/TroubleShooting#6]
**버그를 발견하게 된 과정**
테스트 코드 수정하다가 given에 "this.spec" 에 빨간줄 생겨서 뺐더니 오류가 발생한 것 같음.
java.lang.IllegalStateException: REST Docs configuration not found. Did you forget to add a RestAssuredRestDocumentationConfigurer as a filter when building the RequestSpecification?
	at org.springframework.util.Assert.state(Assert.java:94)
![image](https://user-images.githubusercontent.com/39117025/91143153-05f80780-e6ed-11ea-857c-45648fd52bc7.png)

![image](https://user-images.githubusercontent.com/39117025/91144222-a995e780-e6ee-11ea-91f6-62be833db460.png)

**버그의 원인**
코루틴 스코프 내부라서 오류가 발생하는 것 같음.
코루틴 블럭을 설정하니까 this 가 CoroutineScope 가 되어버렸음.

**문제해결을 위해 시도해본 방법들**
.given(this.spec)  -> .given(spec) 으로 수정

**문제를 해결한 방법**
위 방법으로 해결함.

새로운 오류 발생..

**Comment by mjkim103301** [comment]
### 새로 발견한 오류
org.opentest4j.AssertionFailedError: expected:<[-119, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 8, 0, ...] and 460974 more> but was:<[]>
![image](https://user-images.githubusercontent.com/39117025/91144811-7ef85e80-e6ef-11ea-8737-8963845f1879.png)
### 원인

### 해결방법

**Comment by mjkim103301** [comment]
### 새로 발견한 오류
<pre><code>
Exception in thread "ChannelSystem @coroutine#8" com.sia.core.infra.exception.NotRegisteredException: ReqRenderWithRange is not registered at StandaloneCoroutine
	at com.sia.core.infra.system.channel.CoroutineChannelSystem$request$$inlined$suspendCoroutine$lambda$1.invokeSuspend(CoroutineChannelSystem.kt:53)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
</pre></code>
### 원인

### 해결방법
